spring:
  application:
    name: DataJobConfigProvider
data:
 config:
     path: src/main/resources/
     fileExtension: .yaml
     accessDataSuffix: access_data
     destinationInfoSuffix: destination_details
     jobConfigInfoSuffix: job_configurations
     destinationSupportedFileFormats: avro,parquet,csv
     sourceSupportedFileFormats: json,parquet,csv
     gcsBucket:
    