---
jobName: "TestKafkaStream"
jobDesc: "Description"
source:
  source_type: "KAFKA_STREAM"
  source_url: "localhost:8080"
  topic_name: "kafkatopic"
  topic_type: "json"
  job_Configurations:
  - columns:
    - name: "ID"
      type: "VarChar2()"
      value_range: "1234"
    - name: "name"
      type: "VarChar2()"
      value_range: "Sudeshna"
    - name: "Dept_ID"
      type: "VarChar2()"
      value_range: "1234"
