---
jobName: "TestCSV"
jobDesc: "Description"
source:
  source_type: "FILE_SYSTEM"
  path: "classpath"
  file_Type: "CSV"
  job_Configurations:
  - columns:
    - name: "ID"
      type: "VarChar2()"
      value_range: "1234"
    - name: "name"
      type: "VarChar2()"
      value_range: "Sudeshna"
    - name: "Dept_ID"
      type: "VarChar2()"
      value_range: "1234"
