---
jobName: "TestCSV"
jobDesc: "Description"
source:
  source_type: "FILE_SYSTEM"
  path: "src/main/resources"
  file_Type: "CSV"
  job_Configurations:
  - columns:
    - name: "ID"
      type: "VarChar2()"
      value_range: null
      predicates: null
      joins: null
    - name: "name"
      type: "VarChar2()"
      value_range: "Sudeshna"
      predicates:
      - "LIKE"
      joins: null
    - name: "Dept_ID"
      type: "VarChar2()"
      value_range: null
      predicates: null
      joins: null
